# What crosses a capsule's boundary, measured rather than reasoned about.
#
# capsule's README says a capsule is "not isolation from the host". This script
# is what turns that sentence into a finding: it starts real capsules and asks
# each question from inside one, then writes down the answer that came back.
#
# Every check is a command run inside a capsule started from a generated
# capsule.toml, so the answers describe capsule's actual defaults, not docker's.
#
#   powershell -ExecutionPolicy Bypass -File bench\probe-isolation.ps1
#
# Output: bench\results\isolation.txt, which docs/SANDBOXING.md quotes.

param([string] $Image = 'alpine:3.20')

. (Join-Path $PSScriptRoot 'lib.ps1')
Initialize-Bench
$capsule = Build-Capsule
$out     = Join-Path $PSScriptRoot 'results\isolation.txt'

# A secret in the host environment. If it reaches the capsule, capsule is
# leaking the shell it was launched from, which is the question that matters
# most and cannot be answered by reading the source alone.
$env:CAPSULE_PROBE_SECRET = 'host-secret-do-not-leak'

$dir = New-BenchProject -Image $Image
# A host file the capsule did not create, to test what the bind mount permits.
Set-Content -Path (Join-Path $dir 'host-file.txt') -Value 'written on the host' -Encoding ascii

$checks = [ordered]@{
    'uid/gid inside'            = 'id'
    'hostname'                  = 'hostname'
    'host env leaked in'        = 'env | grep -c CAPSULE_PROBE_SECRET || echo 0'
    'full env inside'           = 'env | sort'
    'project dir is writable'   = 'touch /workspace/made-inside.txt && echo WRITABLE || echo read-only'
    'host file readable'        = 'cat /workspace/host-file.txt'
    'host file writable'        = 'echo appended >> /workspace/host-file.txt && echo WRITABLE || echo read-only'
    'mounts'                    = 'cat /proc/mounts'
    'docker socket present'     = 'test -S /var/run/docker.sock && echo PRESENT || echo absent'
    'outbound network (dns)'    = 'nslookup example.com >/dev/null 2>&1 && echo RESOLVES || echo no-dns'
    'outbound network (tcp)'    = 'nc -z -w 5 1.1.1.1 443 && echo CONNECTS || echo blocked'
    'container loopback is its own' = 'nc -z -w 2 127.0.0.1 __PROBE_PORT__ && echo REACHES-HOST || echo isolated'
    'host service via gateway'  = 'nc -z -w 3 host.docker.internal __PROBE_PORT__ && echo REACHES-HOST || echo blocked'
    'host filesystem visible'   = 'ls / '
    'proc exposure'             = 'ls /proc | head -40'
    'host kernel'               = 'uname -a'
    'host processes visible'    = 'ps -ef | wc -l; ps -ef | head -5'
    'devices'                   = 'ls -l /dev'
    'capabilities'              = 'cat /proc/self/status | grep -i ^Cap'
    'can it mknod'              = 'mknod /tmp/probe-dev c 1 3 2>&1 && echo ALLOWED || echo denied'
    # The container's own /etc is not the host's, so reading a file there proves
    # nothing. What is worth knowing is whether any host path other than the
    # project reached the container, which the mount table answers directly.
    'host paths mounted in'     = 'grep -E " /(workspace|mnt|host)" /proc/mounts || echo "only /workspace"'
    'seccomp mode'              = 'grep -i seccomp /proc/self/status'
    'no_new_privs'              = 'grep -i NoNewPrivs /proc/self/status'
    'cgroup'                    = 'cat /proc/self/cgroup'
    'writable /'                = 'touch /probe-root && echo WRITABLE || echo read-only'
}

# A real TCP listener on the host, so "can a capsule reach a service on the
# machine that started it" is answered by an actual connection rather than by a
# port that happened to be closed.
$listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Any, 0)
$listener.Start()
$probePort = $listener.LocalEndpoint.Port
Write-Host "host listener on port $probePort"

$lines = @()
$lines += "capsule isolation probe"
$lines += "generated by bench\probe-isolation.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss K')"
$lines += "image: $Image"
$lines += "capsule: $((& $capsule --version) 2>&1)"
$lines += "docker: $((Invoke-Docker @('version','--format','{{.Server.Version}} server {{.Server.Os}}/{{.Server.Arch}}')).out.Trim())"
$lines += ""

foreach ($name in $checks.Keys) {
    $cmd = $checks[$name].Replace('__PROBE_PORT__', "$probePort")
    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName               = $capsule
    $psi.Arguments              = ConvertTo-WindowsArgLine @('up', '--', 'sh', '-c', $cmd)
    $psi.WorkingDirectory       = $dir
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError  = $true
    $psi.UseShellExecute        = $false
    $p = [System.Diagnostics.Process]::Start($psi)
    $o = $p.StandardOutput.ReadToEndAsync()
    $e = $p.StandardError.ReadToEndAsync()
    $p.WaitForExit()

    # capsule's own three-line preamble goes to stderr and is not an answer, so
    # only stderr lines that are not the preamble are kept.
    $errText = ($e.Result -split "`r?`n" | Where-Object { $_ -notmatch '^capsule: ' }) -join "`n"

    $lines += "### $name"
    $lines += "\$ capsule up -- sh -c '$cmd'   (exit $($p.ExitCode))"
    $lines += ($o.Result.TrimEnd())
    if ($errText.Trim()) { $lines += "[stderr] " + $errText.Trim() }
    $lines += ""
    Write-Host ("probed: {0}" -f $name)
}

$listener.Stop()

# Did anything the capsule created survive on the host? The one promise. And
# who owns it: a capsule runs as uid 0, so a file it creates in the project
# arrives on the host owned by whoever the mount maps root to.
$lines += "### what the capsule left behind on the host"
$lines += "project directory after all of the above:"
$lines += (Get-ChildItem $dir | ForEach-Object {
    $owner = (Get-Acl $_.FullName).Owner
    "  {0}  owner={1}" -f $_.Name, $owner
})
$lines += ""
$lines += "containers capsule left running:"
$lines += "  " + ((Invoke-Docker @('ps', '-a', '--filter', 'label=me.blinkdev.capsule=1', '--format', '{{.Names}} {{.Status}}')).out.Trim())

Set-Content -Path $out -Value $lines -Encoding utf8
Write-Host "`nwrote $out"
Remove-Item -Recurse -Force $dir
Remove-Item Env:\CAPSULE_PROBE_SECRET
